/******************************************************************************/
/****         Generated by IBExpert 2015.6.1.1 09.02.2026 23:46:11         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE '127.0.0.1/3052:c:\Programy12\MODYFIKACJE\INZYNIERKA\SOURCES\SERVER\database\CENTRAL_WEIGHER.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN DATE_TIME AS
TIMESTAMP;

CREATE DOMAIN FLAG AS
SMALLINT;

CREATE DOMAIN NUMERIC_15_2 AS
NUMERIC(15,2);

CREATE DOMAIN TEXT_10 AS
VARCHAR(10);

CREATE DOMAIN TEXT_100 AS
VARCHAR(100);

CREATE DOMAIN TEXT_25 AS
VARCHAR(25);

CREATE DOMAIN TEXT_50 AS
VARCHAR(50);



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ADDRESSES_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ADDRESSES_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_LOCATIONS_ID TO 1;

CREATE GENERATOR GEN_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_USERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_USERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_WEIGHING_NUMBERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHING_NUMBERS_ID TO 0;



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE GET_ADDRESSES (
    ID_IN INTEGER)
RETURNS (
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_CUSTOMERS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    CUST_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_NEXT_WEIGHING_NO
RETURNS (
    WEIGHING_NO_OUT TEXT_25)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_PRODUCTS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    PROD_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_WEIGHINGS (
    ID_IN INTEGER NOT NULL,
    ID_LOCATION_IN INTEGER)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    CAR_NO_OUT TEXT_25,
    TRAILER_NO_OUT TEXT_25,
    MASS_IN_OUT NUMERIC_15_2,
    DATE_IN_OUT DATE_TIME,
    MASS_OUT_OUT NUMERIC_15_2,
    DATE_OUT_OUT DATE_TIME,
    WEIGHING_TYPE_OUT SMALLINT,
    ID_USER_IN_OUT INTEGER,
    ID_USER_OUT_OUT INTEGER,
    ID_LOCATION_OUT INTEGER,
    ID_USER_INSERT_OUT INTEGER,
    ID_USER_MODIF_OUT INTEGER,
    MODIF_TIME_OUT DATE_TIME,
    IS_DELETED_OUT FLAG,
    PROD_ID_OUT INTEGER,
    PROD_WEIGHING_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG,
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG,
    CUST_ID_OUT INTEGER,
    CUST_WEIGHING_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_ADDRESS (
    ID_IN INTEGER NOT NULL,
    STREET_IN TEXT_50,
    HOUSE_NO_IN TEXT_10,
    LOCAL_NO_IN TEXT_10,
    POST_CODE_IN TEXT_10,
    CITY_IN TEXT_50,
    COUNTRY_IN TEXT_50,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_CUSTOMER (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    NIP_IN TEXT_25,
    PHONE_NO_IN TEXT_25,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_LOCATION (
    ID_IN INTEGER NOT NULL,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_PRODUCT (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    PRICE_IN NUMERIC_15_2,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_USER (
    ID_IN INTEGER NOT NULL,
    LOGIN_IN TEXT_50,
    USER_PASSWORD_IN TEXT_50,
    FIRST_NAME_IN TEXT_25,
    LAST_NAME_IN TEXT_25,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_WEIGHING (
    ID_IN INTEGER NOT NULL,
    CAR_NO_IN TEXT_25,
    TRAILER_NO_IN TEXT_25,
    MASS_IN_IN NUMERIC_15_2,
    DATE_IN_IN DATE_TIME,
    MASS_OUT_IN NUMERIC_15_2,
    DATE_OUT_IN DATE_TIME,
    WEIGHING_TYPE_IN SMALLINT,
    ID_CUSTOMER_IN INTEGER,
    ID_PRODUCT_IN INTEGER,
    ID_USER_IN_IN INTEGER,
    ID_USER_OUT_IN INTEGER,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    ERROR_CODE_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ADDRESSES (
    ID                 INTEGER NOT NULL,
    STREET             TEXT_50,
    HOUSE_NO           TEXT_10,
    LOCAL_NO           TEXT_10,
    POST_CODE          TEXT_10,
    CITY               TEXT_50,
    COUNTRY            TEXT_50,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE CUSTOMERS (
    ID                 INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    NIP                TEXT_25,
    PHONE_NO           TEXT_25,
    ID_ADDRESS         INTEGER,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE CUSTOMERS_LOCATIONS (
    ID           INTEGER NOT NULL,
    ID_CUSTOMER  INTEGER NOT NULL,
    ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE LOCATIONS (
    ID                 INTEGER NOT NULL,
    ID_ADDRESS         INTEGER,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE PRODUCTS (
    ID                 INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    PRICE              NUMERIC_15_2,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE PRODUCTS_LOCATIONS (
    ID           INTEGER NOT NULL,
    ID_PRODUCT   INTEGER NOT NULL,
    ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE USERS (
    ID                 INTEGER NOT NULL,
    LOGIN              TEXT_50,
    USER_PASSWORD      TEXT_100,
    FIRST_NAME         TEXT_25,
    LAST_NAME          TEXT_25,
    ID_LOCATION        INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE WEIGHING_NUMBERS (
    ID            INTEGER NOT NULL,
    WEIGHINGS_NO  INTEGER NOT NULL,
    MONTH_NO      INTEGER NOT NULL,
    YEAR_NO       INTEGER NOT NULL
);

CREATE TABLE WEIGHINGS (
    ID                    INTEGER NOT NULL,
    WEIGHING_NO           TEXT_25,
    CAR_NO                TEXT_25,
    TRAILER_NO            TEXT_25,
    MASS_IN               NUMERIC_15_2,
    DATE_IN               DATE_TIME,
    MASS_OUT              NUMERIC_15_2,
    DATE_OUT              DATE_TIME,
    WEIGHING_TYPE         SMALLINT,
    ID_CUSTOMER           INTEGER,
    ID_CUSTOMER_WEIGHING  INTEGER,
    ID_PRODUCT            INTEGER,
    ID_PRODUCT_WEIGHING   INTEGER,
    ID_USER_IN            INTEGER,
    ID_USER_OUT           INTEGER,
    ID_LOCATION           INTEGER,
    ID_USER_INSERT        INTEGER,
    ID_USER_MODIF         INTEGER,
    MODIFICATION_TIME     DATE_TIME,
    IS_DELETED            FLAG
);

CREATE TABLE WEIGHINGS_ADDRESSESS (
    ID                 INTEGER NOT NULL,
    ID_ADDRESS         INTEGER NOT NULL,
    STREET             TEXT_50,
    HOUSE_NO           TEXT_10,
    LOCAL_NO           TEXT_10,
    POST_CODE          TEXT_10,
    CITY               TEXT_50,
    COUNTRY            TEXT_50,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE WEIGHINGS_CUSTOMERS (
    ID                   INTEGER NOT NULL,
    ID_CUSTOMER          INTEGER NOT NULL,
    CODE                 TEXT_10,
    NAME                 TEXT_50,
    NIP                  TEXT_25,
    PHONE_NO             TEXT_25,
    ID_ADDRESS_WEIGHING  INTEGER,
    ID_USER_INSERT       INTEGER,
    ID_USER_MODIF        INTEGER,
    MODIFICATION_TIME    DATE_TIME,
    IS_DELETED           FLAG
);

CREATE TABLE WEIGHINGS_PRODUCTS (
    ID                 INTEGER NOT NULL,
    ID_PRODUCT         INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    PRICE              NUMERIC_15_2,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ADDRESSES ADD CONSTRAINT PK_ADDRESSES PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS_LOCATIONS ADD CONSTRAINT PK_CUSTOMERS_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS_LOCATIONS ADD CONSTRAINT PK_PRODUCTS_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS ADD CONSTRAINT PK_WEIGHINGS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_ADDRESSESS ADD CONSTRAINT PK_WEIGHINGS_ADDRESSESS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_CUSTOMERS ADD CONSTRAINT PK_WEIGHINGS_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_PRODUCTS ADD CONSTRAINT PK_WEIGHINGS_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE WEIGHING_NUMBERS ADD CONSTRAINT PK_WEIGHING_NUMBERS PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ADDRESSES_BI */
CREATE TRIGGER ADDRESSES_BI FOR ADDRESSES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_addresses_id,1);
end
^

/* Trigger: CUSTOMERS_BI */
CREATE TRIGGER CUSTOMERS_BI FOR CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_id,1);
end
^

/* Trigger: CUSTOMERS_LOCATIONS_BI */
CREATE TRIGGER CUSTOMERS_LOCATIONS_BI FOR CUSTOMERS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_locations_id,1);
end
^

/* Trigger: LOCATIONS_BI */
CREATE TRIGGER LOCATIONS_BI FOR LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_locations_id,1);
end
^

/* Trigger: PRODUCTS_BI */
CREATE TRIGGER PRODUCTS_BI FOR PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_id,1);
end
^

/* Trigger: PRODUCTS_LOCATIONS_BI */
CREATE TRIGGER PRODUCTS_LOCATIONS_BI FOR PRODUCTS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_locations_id,1);
end
^

/* Trigger: USERS_BI */
CREATE TRIGGER USERS_BI FOR USERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_users_id,1);
end
^

/* Trigger: WEIGHINGS_ADDRESSESS_BI */
CREATE TRIGGER WEIGHINGS_ADDRESSESS_BI FOR WEIGHINGS_ADDRESSESS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_addressess_id,1);
end
^

/* Trigger: WEIGHINGS_BI */
CREATE TRIGGER WEIGHINGS_BI FOR WEIGHINGS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_id,1);
end
^

/* Trigger: WEIGHINGS_CUSTOMERS_BI */
CREATE TRIGGER WEIGHINGS_CUSTOMERS_BI FOR WEIGHINGS_CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_customers_id,1);
end
^

/* Trigger: WEIGHINGS_PRODUCTS_BI */
CREATE TRIGGER WEIGHINGS_PRODUCTS_BI FOR WEIGHINGS_PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_products_id,1);
end
^

/* Trigger: WEIGHING_NUMBERS_BI */
CREATE TRIGGER WEIGHING_NUMBERS_BI FOR WEIGHING_NUMBERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighing_numbers_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE GET_ADDRESSES (
    ID_IN INTEGER)
RETURNS (
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
      ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED
    FROM ADDRESSES
    WHERE
      (ID = :id_in) and (is_deleted = 0)
    INTO
      :address_id_out, :address_street_out, :address_house_no_out,
      :address_local_no_out, :address_post_code_out, :address_city_out,
      :address_country_out, :address_id_user_insert_out, :address_id_user_modif_out,
      :address_modif_time_out, :address_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
      ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED
    FROM ADDRESSES
    WHERE
      (is_deleted = 0)
    INTO
      :address_id_out, :address_street_out, :address_house_no_out,
      :address_local_no_out, :address_post_code_out, :address_city_out,
      :address_country_out, :address_id_user_insert_out, :address_id_user_modif_out,
      :address_modif_time_out, :address_is_deleted_out
    do begin
      suspend;
      address_id_out = null; address_street_out = null; address_house_no_out = null;
      address_local_no_out = null; address_post_code_out = null; address_city_out = null;
      address_country_out = null; address_id_user_insert_out = null; address_id_user_modif_out = null;
      address_modif_time_out = null; address_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_CUSTOMERS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    CUST_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      C.ID, C.CODE, C.NAME, C.NIP, C.PHONE_NO, C.ID_ADDRESS, C.ID_USER_INSERT,
      C.ID_USER_MODIF, C.MODIFICATION_TIME, C.IS_DELETED
    FROM customers C
    LEFT join customers_locations CL on CL.id_customer = C.ID
    WHERE
      (C.ID = :id_in) and (C.is_deleted = 0) and (coalesce(CL.id_location, 0) = :id_location_in)
    INTO
      :cust_id_out, :cust_code_out, :cust_name_out, :cust_nip_out, :cust_phone_no_out,
      :cust_id_address_out, :cust_id_user_insert_out, :cust_id_user_modif_out,
      :cust_modif_time_out, :cust_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      C.ID, C.CODE, C.NAME, C.NIP, C.PHONE_NO, C.ID_ADDRESS, C.ID_USER_INSERT,
      C.ID_USER_MODIF, C.MODIFICATION_TIME, C.IS_DELETED
    FROM customers C
    LEFT join customers_locations CL on CL.id_customer = C.ID
    WHERE
      (C.is_deleted = 0) and (coalesce(CL.id_location, 0) = :id_location_in)
    INTO
      :cust_id_out, :cust_code_out, :cust_name_out, :cust_nip_out, :cust_phone_no_out,
      :cust_id_address_out, :cust_id_user_insert_out, :cust_id_user_modif_out,
      :cust_modif_time_out, :cust_is_deleted_out
    do begin
      suspend;
      cust_id_out = null; cust_code_out = null; cust_name_out = null; cust_nip_out = null;
      cust_phone_no_out = null; cust_id_address_out = null; cust_id_user_insert_out = null;
      cust_id_user_modif_out = null; cust_modif_time_out = null; cust_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_NEXT_WEIGHING_NO
RETURNS (
    WEIGHING_NO_OUT TEXT_25)
AS
declare variable TMP_MONTH integer;
declare variable TMP_YEAR integer;
declare variable TMP_DT DATE_TIME;
declare variable TMP_WEIGHING_NO integer;
begin
  tmp_dt = 'now';
  tmp_year = extract(year from tmp_dt);
  tmp_month = extract(month from tmp_dt);

  select
    weighings_no
  from weighing_numbers
  where
    (month_no = :tmp_month) and (year_no = :tmp_year)
  into
    :tmp_weighing_no;

  if (coalesce(:tmp_weighing_no, 0) = 0) then
  begin
    tmp_weighing_no = 1;
    INSERT INTO WEIGHING_NUMBERS
      (WEIGHINGS_NO, MONTH_NO, YEAR_NO)
    VALUES
      (:tmp_weighing_no, :tmp_month, :tmp_year);
  end else
  begin
    tmp_weighing_no = :tmp_weighing_no + 1;
    UPDATE weighing_numbers
    SET weighings_no = :tmp_weighing_no
    where
      (month_no = :tmp_month) and (year_no = :tmp_year);
  end

  weighing_no_out = LEFT(CAST(tmp_weighing_no as text_10) || '/' || cast(tmp_month as varchar(5)) || '/' || CAST(tmp_year as varchar(5)), 25);
  suspend;
end^


ALTER PROCEDURE GET_PRODUCTS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    PROD_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      P.ID, P.CODE, P.NAME, P.PRICE, P.ID_USER_INSERT, P.ID_USER_MODIF,
      P.MODIFICATION_TIME, P.IS_DELETED
    FROM products P
    LEFT join products_locations PL on PL.id_product = P.ID
    WHERE
      (P.ID = :id_in) and (P.is_deleted = 0) and (coalesce(PL.id_location, 0) = :id_location_in)
    INTO
      :prod_id_out, :prod_code_out, :prod_name_out, :prod_price_out, :prod_id_user_insert_out,
      :prod_id_user_modif_out, :prod_modif_time_out, :prod_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      P.ID, P.CODE, P.NAME, P.PRICE, P.ID_USER_INSERT, P.ID_USER_MODIF,
      P.MODIFICATION_TIME, P.IS_DELETED
    FROM products P
    LEFT join products_locations PL on PL.id_product = P.ID
    WHERE
      (P.is_deleted = 0) and (coalesce(PL.id_location, 0) = :id_location_in)
    INTO
      :prod_id_out, :prod_code_out, :prod_name_out, :prod_price_out, :prod_id_user_insert_out,
      :prod_id_user_modif_out, :prod_modif_time_out, :prod_is_deleted_out
    do begin
      suspend;
      prod_id_out = null; prod_code_out = null; prod_name_out = null; prod_price_out = null;
      prod_id_user_insert_out = null; prod_id_user_modif_out = null; prod_modif_time_out = null;
      prod_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_WEIGHINGS (
    ID_IN integer not null,
    ID_LOCATION_IN integer)
returns (
    ID_OUT integer,
    WEIGHING_NO_OUT TEXT_25,
    CAR_NO_OUT TEXT_25,
    TRAILER_NO_OUT TEXT_25,
    MASS_IN_OUT NUMERIC_15_2,
    DATE_IN_OUT DATE_TIME,
    MASS_OUT_OUT NUMERIC_15_2,
    DATE_OUT_OUT DATE_TIME,
    WEIGHING_TYPE_OUT smallint,
    ID_USER_IN_OUT integer,
    ID_USER_OUT_OUT integer,
    ID_LOCATION_OUT integer,
    ID_USER_INSERT_OUT integer,
    ID_USER_MODIF_OUT integer,
    MODIF_TIME_OUT DATE_TIME,
    IS_DELETED_OUT FLAG,
    PROD_ID_OUT INTEGER,
    PROD_WEIGHING_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG,
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG,
    CUST_ID_OUT INTEGER,
    CUST_WEIGHING_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
as
begin
  if (:id_in != 0) then
  begin
    SELECT
       W.ID, W.WEIGHING_NO, W.CAR_NO, W.TRAILER_NO, W.MASS_IN, W.DATE_IN,
       W.MASS_OUT, W.DATE_OUT, W.WEIGHING_TYPE, W.ID_USER_IN, W.ID_USER_OUT,
       W.ID_LOCATION, W.ID_USER_INSERT, W.ID_USER_MODIF, W.MODIFICATION_TIME,
       W.IS_DELETED,

       WP.ID, WP.ID_PRODUCT, WP.CODE, WP.NAME, WP.PRICE, WP.ID_USER_INSERT,
       WP.ID_USER_MODIF, WP.MODIFICATION_TIME, WP.IS_DELETED,

       WC.ID, WC.ID_CUSTOMER, WC.CODE, WC.NAME, WC.NIP, WC.PHONE_NO, WC.ID_ADDRESS_WEIGHING,
       WC.ID_USER_INSERT, WC.ID_USER_MODIF, WC.MODIFICATION_TIME, WC.IS_DELETED,

       ADDRSS.ID, ADDRSS.STREET, ADDRSS.HOUSE_NO, ADDRSS.LOCAL_NO, ADDRSS.POST_CODE,
       ADDRSS.CITY, ADDRSS.COUNTRY, ADDRSS.ID_USER_INSERT, ADDRSS.ID_USER_MODIF,
       ADDRSS.MODIFICATION_TIME, ADDRSS.IS_DELETED
    FROM
      WEIGHINGS W
    LEFT JOIN WEIGHINGS_PRODUCTS WP ON WP.ID = W.ID_PRODUCT_WEIGHING
    LEFT JOIN WEIGHINGS_CUSTOMERS WC ON WC.ID = W.ID_CUSTOMER_WEIGHING
    LEFT JOIN ADDRESSES ADDRSS ON ADDRSS.ID = WC.id_address_weighing
    WHERE
      (W.ID = :id_in) and (W.is_deleted = 0) and (coalesce(W.id_location, 0) = :id_location_in)
    INTO
      :ID_OUT, :WEIGHING_NO_OUT, :CAR_NO_OUT, :TRAILER_NO_OUT, :MASS_IN_OUT, :DATE_IN_OUT,
      :MASS_OUT_OUT, :DATE_OUT_OUT, :WEIGHING_TYPE_OUT, :ID_USER_IN_OUT, :ID_USER_OUT_OUT,
      :ID_LOCATION_OUT, :ID_USER_INSERT_OUT, :ID_USER_MODIF_OUT, :MODIF_TIME_OUT, :IS_DELETED_OUT,

      :PROD_WEIGHING_ID_OUT, :PROD_ID_OUT, :PROD_CODE_OUT, :PROD_NAME_OUT, :PROD_PRICE_OUT,
      :PROD_ID_USER_INSERT_OUT, :PROD_ID_USER_MODIF_OUT, :PROD_MODIF_TIME_OUT,
      :PROD_IS_DELETED_OUT,

      :CUST_WEIGHING_ID_OUT, :CUST_ID_OUT, :CUST_CODE_OUT, :CUST_NAME_OUT,
      :CUST_NIP_OUT, :CUST_PHONE_NO_OUT, :CUST_ID_ADDRESS_OUT, :CUST_ID_USER_INSERT_OUT,
      :CUST_ID_USER_MODIF_OUT, :CUST_MODIF_TIME_OUT, :CUST_IS_DELETED_OUT,

      :ADDRESS_ID_OUT, :ADDRESS_STREET_OUT, :ADDRESS_HOUSE_NO_OUT,
      :ADDRESS_LOCAL_NO_OUT, :ADDRESS_POST_CODE_OUT, :ADDRESS_CITY_OUT,
      :ADDRESS_COUNTRY_OUT, :ADDRESS_ID_USER_INSERT_OUT, :ADDRESS_ID_USER_MODIF_OUT,
      :ADDRESS_MODIF_TIME_OUT, :ADDRESS_IS_DELETED_OUT;

    suspend;
    exit;
  end else
  begin
    FOR SELECT
       W.ID, W.WEIGHING_NO, W.CAR_NO, W.TRAILER_NO, W.MASS_IN, W.DATE_IN,
       W.MASS_OUT, W.DATE_OUT, W.WEIGHING_TYPE, W.ID_USER_IN, W.ID_USER_OUT,
       W.ID_LOCATION, W.ID_USER_INSERT, W.ID_USER_MODIF, W.MODIFICATION_TIME,
       W.IS_DELETED,

       WP.ID, WP.ID_PRODUCT, WP.CODE, WP.NAME, WP.PRICE, WP.ID_USER_INSERT,
       WP.ID_USER_MODIF, WP.MODIFICATION_TIME, WP.IS_DELETED,

       WC.ID, WC.ID_CUSTOMER, WC.CODE, WC.NAME, WC.NIP, WC.PHONE_NO, WC.ID_ADDRESS_WEIGHING,
       WC.ID_USER_INSERT, WC.ID_USER_MODIF, WC.MODIFICATION_TIME, WC.IS_DELETED,

       ADDRSS.ID, ADDRSS.STREET, ADDRSS.HOUSE_NO, ADDRSS.LOCAL_NO, ADDRSS.POST_CODE,
       ADDRSS.CITY, ADDRSS.COUNTRY, ADDRSS.ID_USER_INSERT, ADDRSS.ID_USER_MODIF,
       ADDRSS.MODIFICATION_TIME, ADDRSS.IS_DELETED
    FROM
      WEIGHINGS W
    LEFT JOIN WEIGHINGS_PRODUCTS WP ON WP.ID = W.ID_PRODUCT_WEIGHING
    LEFT JOIN WEIGHINGS_CUSTOMERS WC ON WC.ID = W.ID_CUSTOMER_WEIGHING
    LEFT JOIN ADDRESSES ADDRSS ON ADDRSS.ID = WC.id_address_weighing
    WHERE
      (W.is_deleted = 0) and (coalesce(W.id_location, 0) = :id_location_in)
    INTO
      :ID_OUT, :WEIGHING_NO_OUT, :CAR_NO_OUT, :TRAILER_NO_OUT, :MASS_IN_OUT, :DATE_IN_OUT,
      :MASS_OUT_OUT, :DATE_OUT_OUT, :WEIGHING_TYPE_OUT, :ID_USER_IN_OUT, :ID_USER_OUT_OUT,
      :ID_LOCATION_OUT, :ID_USER_INSERT_OUT, :ID_USER_MODIF_OUT, :MODIF_TIME_OUT, :IS_DELETED_OUT,

      :PROD_WEIGHING_ID_OUT, :PROD_ID_OUT, :PROD_CODE_OUT, :PROD_NAME_OUT, :PROD_PRICE_OUT,
      :PROD_ID_USER_INSERT_OUT, :PROD_ID_USER_MODIF_OUT, :PROD_MODIF_TIME_OUT,
      :PROD_IS_DELETED_OUT,

      :CUST_WEIGHING_ID_OUT, :CUST_ID_OUT, :CUST_CODE_OUT, :CUST_NAME_OUT,
      :CUST_NIP_OUT, :CUST_PHONE_NO_OUT, :CUST_ID_ADDRESS_OUT, :CUST_ID_USER_INSERT_OUT,
      :CUST_ID_USER_MODIF_OUT, :CUST_MODIF_TIME_OUT, :CUST_IS_DELETED_OUT,

      :ADDRESS_ID_OUT, :ADDRESS_STREET_OUT, :ADDRESS_HOUSE_NO_OUT,
      :ADDRESS_LOCAL_NO_OUT, :ADDRESS_POST_CODE_OUT, :ADDRESS_CITY_OUT,
      :ADDRESS_COUNTRY_OUT, :ADDRESS_ID_USER_INSERT_OUT, :ADDRESS_ID_USER_MODIF_OUT,
      :ADDRESS_MODIF_TIME_OUT, :ADDRESS_IS_DELETED_OUT
    do begin
      suspend;
      ID_OUT = null; WEIGHING_NO_OUT = null; CAR_NO_OUT = null; TRAILER_NO_OUT = null; MASS_IN_OUT = null;
      DATE_IN_OUT = null; MASS_OUT_OUT = null; DATE_OUT_OUT = null; WEIGHING_TYPE_OUT = null;
      ID_USER_IN_OUT = null; ID_USER_OUT_OUT = null; ID_LOCATION_OUT = null; ID_USER_INSERT_OUT = null;
      ID_USER_MODIF_OUT = null; MODIF_TIME_OUT = null; IS_DELETED_OUT = null;
        
      PROD_WEIGHING_ID_OUT = null; PROD_ID_OUT = null; PROD_CODE_OUT = null; PROD_NAME_OUT = null;
      PROD_PRICE_OUT = null; PROD_ID_USER_INSERT_OUT = null; PROD_ID_USER_MODIF_OUT = null;
      PROD_MODIF_TIME_OUT = null; PROD_IS_DELETED_OUT = null;
        
      CUST_WEIGHING_ID_OUT = null; CUST_ID_OUT = null; CUST_CODE_OUT = null;
      CUST_NAME_OUT = null; CUST_NIP_OUT = null; CUST_PHONE_NO_OUT = null;
      CUST_ID_ADDRESS_OUT = null; CUST_ID_USER_INSERT_OUT = null; CUST_ID_USER_MODIF_OUT = null;
      CUST_MODIF_TIME_OUT = null; CUST_IS_DELETED_OUT = null;
        
      ADDRESS_ID_OUT = null; ADDRESS_STREET_OUT = null;
      ADDRESS_HOUSE_NO_OUT = null; ADDRESS_LOCAL_NO_OUT = null;
      ADDRESS_POST_CODE_OUT = null; ADDRESS_CITY_OUT = null;
      ADDRESS_COUNTRY_OUT = null; ADDRESS_ID_USER_INSERT_OUT = null;
      ADDRESS_ID_USER_MODIF_OUT = null; ADDRESS_MODIF_TIME_OUT = null;
      ADDRESS_IS_DELETED_OUT = null;
    end
  end
end^


ALTER PROCEDURE INSERT_UPDATE_ADDRESS (
    ID_IN INTEGER NOT NULL,
    STREET_IN TEXT_50,
    HOUSE_NO_IN TEXT_10,
    LOCAL_NO_IN TEXT_10,
    POST_CODE_IN TEXT_10,
    CITY_IN TEXT_50,
    COUNTRY_IN TEXT_50,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_addresses_id, 1);
    INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES (:id_out, :street_in, :house_no_in, :local_no_in, :post_code_in, :city_in, :country_in, :id_user_in, :id_user_in, 'NOW', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE ADDRESSES
      SET STREET = :street_in,
          HOUSE_NO = :house_no_in,
          LOCAL_NO = :local_no_in,
          POST_CODE = :post_code_in,
          CITY = :city_in,
          COUNTRY = :country_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE addresses
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_CUSTOMER (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    NIP_IN TEXT_25,
    PHONE_NO_IN TEXT_25,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_customers_id, 1);
    INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES(:id_out, :code_in, :name_in, :nip_in, :phone_no_in, :id_address_in, :id_user_in, :id_user_in, 'now', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE customers
      SET CODE = :CODE_IN,
          NAME = :NAME_IN,
          NIP = :NIP_IN,
          PHONE_NO = :PHONE_NO_IN,
          ID_ADDRESS = :ID_ADDRESS_IN,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE customers
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_LOCATION (
    ID_IN INTEGER NOT NULL,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_locations_id, 1);
    INSERT INTO LOCATIONS (ID, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES (:id_out, :id_address_in, :id_user_in, :id_user_in, 'now', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE LOCATIONS
      SET ID_ADDRESS = :id_address_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE locations
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_PRODUCT (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    PRICE_IN NUMERIC_15_2,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_products_id, 1);
    INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES(:id_out, :code_in, :name_in, :price_in, :id_user_in, :id_user_in, 'NOW', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE PRODUCTS
      SET CODE = :code_in,
          NAME = :name_in,
          PRICE = :price_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE PRODUCTS
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_USER (
    ID_IN INTEGER NOT NULL,
    LOGIN_IN TEXT_50,
    USER_PASSWORD_IN TEXT_100,
    FIRST_NAME_IN TEXT_25,
    LAST_NAME_IN TEXT_25,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_users_id, 1);
    INSERT INTO USERS (ID, LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME, ID_LOCATION, MODIFICATION_TIME, IS_DELETED)
      VALUES (:ID_OUT, :LOGIN_IN, :USER_PASSWORD_IN, :FIRST_NAME_IN, :LAST_NAME_IN, :ID_LOCATION_IN, 'now', :IS_DELETED_IN);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE users
      SET LOGIN = :login_in,
          USER_PASSWORD = :user_password_in,
          FIRST_NAME = :first_name_in,
          LAST_NAME = :last_name_in,
          ID_LOCATION = :id_location_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE users
      SET is_deleted = 1,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_WEIGHING (
    ID_IN INTEGER NOT NULL,
    CAR_NO_IN TEXT_25,
    TRAILER_NO_IN TEXT_25,
    MASS_IN_IN NUMERIC_15_2,
    DATE_IN_IN DATE_TIME,
    MASS_OUT_IN NUMERIC_15_2,
    DATE_OUT_IN DATE_TIME,
    WEIGHING_TYPE_IN SMALLINT,
    ID_CUSTOMER_IN INTEGER,
    ID_PRODUCT_IN INTEGER,
    ID_USER_IN_IN INTEGER,
    ID_USER_OUT_IN INTEGER,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    ERROR_CODE_OUT INTEGER)
AS
declare variable TMP_WEIGHING_NO TEXT_25;
declare variable TMP_CUSTOMER_CODE TEXT_10;
declare variable TMP_CUSTOMER_NAME TEXT_50;
declare variable TMP_CUSTOMER_NIP TEXT_25;
declare variable TMP_CUSTOMER_PHONE_NO TEXT_25;
declare variable TMP_ID_ADDRESS integer;
declare variable TMP_ADDRESS_STREET TEXT_50;
declare variable TMP_ADDRESS_HOUSE_NO TEXT_10;
declare variable TMP_ADDRESS_LOCAL_NO TEXT_10;
declare variable TMP_ADDRESS_POST_CODE TEXT_10;
declare variable TMP_ADDRESS_CITY TEXT_50;
declare variable TMP_ADDRESS_COUNTRY TEXT_50;
declare variable TMP_PRODUCT_CODE TEXT_10;
declare variable TMP_PRODUCT_NAME TEXT_50;
declare variable TMP_PRODUCT_PRICE NUMERIC_15_2;
declare variable TMP_ID1 integer;
declare variable TMP_ID2 integer;
begin
  id_out = 0;
  error_code_out = 1;
  weighing_no_out = '';
  if (:id_in = 0) then
  begin
    if (:weighing_type_in = 1) then
    begin
      error_code_out = -1; -- drugie wazenie przy braku pierwszego wazenia
      suspend;
      exit;
    end else if (:weighing_type_in in (0, 2)) then
    begin
      -- if (coalesce(:id_location_in, 0) = 0)  then
      -- begin
      --   error_code_out = -2;
      --   suspend;
      --   exit;
      -- end

      -- POBRANIE DANYCH KARTOTEK
      -- KONTRAHENT
      if (coalesce(:id_customer_in, 0) = 0)  then
      begin
        error_code_out = -3;
        suspend;
        exit;
      end

      SELECT
        CUST_CODE_OUT, CUST_NAME_OUT, CUST_NIP_OUT, CUST_PHONE_NO_OUT, CUST_ID_ADDRESS_OUT
      FROM get_customers(:id_customer_in, :id_location_in)
      INTO
        :tmp_customer_code, :tmp_customer_name, :tmp_customer_nip, :tmp_customer_phone_no,
        :tmp_id_address;

      SELECT
        ADDRESS_STREET_OUT, ADDRESS_HOUSE_NO_OUT, ADDRESS_LOCAL_NO_OUT, ADDRESS_POST_CODE_OUT,
        ADDRESS_CITY_OUT, ADDRESS_COUNTRY_OUT
      FROM get_addresses(:tmp_id_address)
      INTO
        :tmp_address_street, :tmp_address_house_no, :tmp_address_local_no, :tmp_address_post_code,
        :tmp_address_city, :tmp_address_country;

      -- PRODUKT
      if (coalesce(:id_product_in, 0) = 0)  then
      begin
        error_code_out = -4;
        suspend;
        exit;
      end

      SELECT
        PROD_CODE_OUT, PROD_NAME_OUT, PROD_PRICE_OUT
      FROM get_products(:id_product_in, :id_location_in)
      INTO
        :tmp_product_code, :tmp_product_name, :tmp_product_price;

      -- insert adres
      tmp_id1 = gen_id(gen_weighings_addressess_id, 1);
      INSERT INTO WEIGHINGS_ADDRESSESS
        (ID, ID_ADDRESS, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
         ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES
        (:tmp_id1, :tmp_id_address, :tmp_address_street, :tmp_address_house_no, :tmp_address_local_no,
         :tmp_address_post_code, :tmp_address_city, :tmp_address_country, :id_user_in_in,
         :id_user_in_in, 'now', 0);

      -- insert customer
      tmp_id2 = gen_id(gen_weighings_customers_id, 1);
      INSERT INTO WEIGHINGS_CUSTOMERS
        (ID, ID_CUSTOMER, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS_WEIGHING, ID_USER_INSERT,
         ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES
        (:tmp_id2, :id_customer_in, :tmp_customer_code, :tmp_customer_name, :tmp_customer_nip,
         :tmp_customer_phone_no, :tmp_id1, :id_user_in_in, :id_user_in_in, 'now', 0);

      -- insert product
      tmp_id1 = gen_id(gen_weighings_products_id, 1);
      INSERT INTO WEIGHINGS_PRODUCTS
        (ID, ID_PRODUCT, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME,
         IS_DELETED)
      VALUES
        (:tmp_id1, :id_product_in, :tmp_product_code, :tmp_product_name, :tmp_product_price,
         :id_user_in_in, :id_user_in_in, 'now', 0);

      -- numer wazenia
      SELECT weighing_no_out FROM get_next_weighing_no into :tmp_weighing_no;

      -- wazenie
      id_out = gen_id(gen_weighings_id, 1);
      if (:weighing_type_in = 0) then
      begin
        -- PIERWSZE WAZENIE
        INSERT INTO WEIGHINGS
          (ID, WEIGHING_NO, CAR_NO, TRAILER_NO, MASS_IN, DATE_IN, MASS_OUT, DATE_OUT, WEIGHING_TYPE,
           ID_CUSTOMER, ID_CUSTOMER_WEIGHING, ID_PRODUCT, ID_PRODUCT_WEIGHING, ID_USER_IN, ID_USER_OUT,
           ID_LOCATION, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
        VALUES
          (:id_out, :tmp_weighing_no, :car_no_in, :trailer_no_in, :mass_in_in, :date_in_in, NULL, NULL,
           :weighing_type_in, :id_customer_in, :tmp_id2, :id_product_in, :tmp_id1, :id_user_in_in, NULL,
           :id_location_in, :id_user_in_in, :id_user_in_in, 'now', 0);

        weighing_no_out = :tmp_weighing_no;
      end else if (:weighing_type_in = 2) then
      begin
        -- WAZENIE POJEDYNCZE
        INSERT INTO WEIGHINGS
          (ID, WEIGHING_NO, CAR_NO, TRAILER_NO, MASS_IN, DATE_IN, MASS_OUT, DATE_OUT, WEIGHING_TYPE,
           ID_CUSTOMER, ID_CUSTOMER_WEIGHING, ID_PRODUCT, ID_PRODUCT_WEIGHING, ID_USER_IN, ID_USER_OUT,
           ID_LOCATION, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
        VALUES
          (:id_out, :tmp_weighing_no, :car_no_in, :trailer_no_in, :mass_in_in, :date_in_in, :mass_out_in,
           NULL, :weighing_type_in, :id_customer_in, :tmp_id2, :id_product_in, :tmp_id1, :id_user_in_in,
           NULL, :id_location_in, :id_user_in_in, :id_user_in_in, 'now', 0);

        weighing_no_out = :tmp_weighing_no;
      end
    end
  end else
  begin
    if ((:is_deleted_in = 0) and (:weighing_type_in = 1)) then
    begin
      -- DRUGIE WAZENIE
      UPDATE weighings
      SET MASS_OUT = :mass_out_in,
          DATE_OUT = :date_out_in,
          ID_USER_OUT = :id_user_out_in,
          WEIGHING_TYPE = :weighing_type_in,
          ID_USER_MODIF = :id_user_out_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (WEIGHING_TYPE = 0) and (is_deleted = 0);
      id_out = :id_in;
      select weighing_no from weighings where (ID = :id_in) into weighing_no_out;
    end else if (:is_deleted_in = 1) then
    begin
      UPDATE weighings
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);

      id_out = :id_in;
      select weighing_no from weighings where (ID = :id_in) into weighing_no_out;
    end else
    begin
      error_code_out = -5;
    end
  end
  suspend;
end^



SET TERM ; ^

COMMIT WORK;

execute procedure INSERT_UPDATE_USER(0, 'Admin', 'ba0020fb1e1371474d5b328a53b87d2a05db7b8320f546baaf5dcbb248ef0c60', '', '', 0, 0);
execute procedure INSERT_UPDATE_ADDRESS(0, '---', '---', '---', '---', '---', '---', 0, 1);
execute procedure INSERT_UPDATE_CUSTOMER(0, '---', '---', '---', '---', 1, 0, 1);
execute procedure INSERT_UPDATE_PRODUCT(0, '---', '---', 0.0, 0, 1);

COMMIT WORK;