/******************************************************************************/
/****         Generated by IBExpert 2015.6.1.1 09.02.2026 23:46:11         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE '127.0.0.1/3052:C:\Programy12\MODYFIKACJE\IN¯YNIERKA\SOURCES\SERVER\database\CENTRAL_WEIGHER.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN DATE_TIME AS
TIMESTAMP;

CREATE DOMAIN FLAG AS
SMALLINT
CHECK (value in (0,1));

CREATE DOMAIN NUMERIC_15_2 AS
NUMERIC(15,2);

CREATE DOMAIN TEXT_10 AS
VARCHAR(10);

CREATE DOMAIN TEXT_100 AS
VARCHAR(100);

CREATE DOMAIN TEXT_50 AS
VARCHAR(50);

CREATE DOMAIN TEXT_25 AS
VARCHAR(25);



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ADDRESSES_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ADDRESSES_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_USERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_USERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_LOCATIONS_ID TO 0;



/******************************************************************************/
/****                           Package headers                            ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PACKAGE RDB$BLOB_UTIL
AS
^


CREATE PACKAGE RDB$PROFILER
AS
^


CREATE PACKAGE RDB$TIME_ZONE_UTIL
AS
^



SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ADDRESSES (
    ID  INTEGER NOT NULL,
    STREET  TEXT_50,
    HOUSE_NO  TEXT_10,
    LOCAL_NO  TEXT_10,
    POST_CODE  TEXT_10,
    CITY  TEXT_50,
    COUNTRY  TEXT_50,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE CUSTOMERS (
    ID  INTEGER NOT NULL,
    CODE  TEXT_10,
    NAME  TEXT_50,
    NIP  TEXT_25,
    PHONE_NO  TEXT_25,
    ID_ADDRESS  INTEGER,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE CUSTOMERS_LOCATIONS (
    ID  INTEGER NOT NULL,
	ID_CUSTOMER  INTEGER NOT NULL,
	ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE LOCATIONS (
    ID  INTEGER NOT NULL,
    ID_ADDRESS  INTEGER,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE PRODUCTS (
    ID  INTEGER NOT NULL,
    CODE  TEXT_10,
    NAME  TEXT_50,
    PRICE  NUMERIC_15_2,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE PRODUCTS_LOCATIONS (
    ID INTEGER  NOT NULL,
	ID_PRODUCT  INTEGER NOT NULL,
	ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE USERS (
    ID  INTEGER NOT NULL,
	LOGIN  TEXT_50,
	PASSWORD  TEXT_50,
	FIRST_NAME  TEXT_25,
	LAST_NAME  TEXT_25,
	ID_LOCATION  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE WEIGHINGS (
    ID  INTEGER NOT NULL,
    WEIGHING_NO  TEXT_25,
    CAR_NO  TEXT_25,
    TRAILER_NO  TEXT_25,
    MASS_IN  NUMERIC_15_2,
    DATE_IN  DATE_TIME,
    MASS_OUT  NUMERIC_15_2,
    DATE_OUT  DATE_TIME,
    WEIGHING_TYPE  SMALLINT,
	ID_CUSTOMER  INTEGER,
	ID_CUSTOMER_WEIGHING  INTEGER,
    ID_USER_IN  INTEGER,
    ID_USER_OUT  INTEGER,
    ID_LOCATION  INTEGER,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE WEIGHINGS_ADDRESSESS (
    ID  INTEGER NOT NULL,
    ID_ADDRESS  INTEGER NOT NULL,
    STREET  TEXT_50,
    HOUSE_NO  TEXT_10,
    LOCAL_NO  TEXT_10,
    POST_CODE  TEXT_10,
    CITY  TEXT_50,
    COUNTRY  TEXT_50,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE WEIGHINGS_CUSTOMERS (
    ID  INTEGER NOT NULL,
    ID_CUSTOMER  INTEGER NOT NULL,
    CODE  TEXT_10,
    NAME  TEXT_50,
    NIP  TEXT_25,
    PHONE_NO  TEXT_25,
    ID_ADDRESS_WEIGHING  INTEGER,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);

CREATE TABLE WEIGHINGS_PRODUCTS (
    ID  INTEGER NOT NULL,
    ID_PRODUCT  INTEGER NOT NULL,
    CODE  TEXT_10,
    NAME  TEXT_50,
    PRICE  NUMERIC_15_2,
    ID_USER_INSERT  INTEGER,
    ID_USER_MODIF  INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED  FLAG NOT NULL
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ADDRESSES ADD CONSTRAINT PK_ADDRESSES PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS ADD CONSTRAINT PK_WEIGHINGS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_ADDRESSESS ADD CONSTRAINT PK_WEIGHINGS_ADDRESSESS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_CUSTOMERS ADD CONSTRAINT PK_WEIGHINGS_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_PRODUCTS ADD CONSTRAINT PK_WEIGHINGS_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS_LOCATIONS ADD CONSTRAINT PK_PRODUCTS_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS_LOCATIONS ADD CONSTRAINT PK_PRODUCTS_LOCATIONS PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ADDRESSES_BI */
CREATE TRIGGER ADDRESSES_BI FOR ADDRESSES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_addresses_id,1);
end
^

/* Trigger: CUSTOMERS_BI */
CREATE TRIGGER CUSTOMERS_BI FOR CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_id,1);
end
^

/* Trigger: CUSTOMERS_LOCATIONS_BI */
CREATE TRIGGER CUSTOMERS_LOCATIONS_BI FOR CUSTOMERS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_locations_id,1);
end
^

/* Trigger: LOCATIONS_BI */
CREATE TRIGGER LOCATIONS_BI FOR LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_locations_id,1);
end
^

/* Trigger: PRODUCTS_BI */
CREATE TRIGGER PRODUCTS_BI FOR PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_id,1);
end
^

/* Trigger: PRODUCTS_LOCATIONS_BI */
CREATE TRIGGER PRODUCTS_LOCATIONS_BI FOR PRODUCTS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_locations_id,1);
end
^

/* Trigger: WEIGHINGS_BI */
CREATE TRIGGER WEIGHINGS_BI FOR WEIGHINGS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_id,1);
end
^

/* Trigger: WEIGHINGS_ADDRESSESS_BI */
CREATE TRIGGER WEIGHINGS_ADDRESSESS_BI FOR WEIGHINGS_ADDRESSESS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_addressess_id,1);
end
^

/* Trigger: WEIGHINGS_CUSTOMERS_BI */
CREATE TRIGGER WEIGHINGS_CUSTOMERS_BI FOR WEIGHINGS_CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_customers_id,1);
end
^

/* Trigger: WEIGHINGS_PRODUCTS_BI */
CREATE TRIGGER WEIGHINGS_PRODUCTS_BI FOR WEIGHINGS_PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_products_id,1);
end
^

/* Trigger: USERS_BI */
CREATE TRIGGER USERS_BI FOR USERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_users_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                           Package headers                            ****/
/******************************************************************************/



SET TERM ^ ;


SET TERM ; ^



/******************************************************************************/
/****                            Package bodies                            ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PACKAGE BODY RDB$BLOB_UTIL
AS
^


CREATE PACKAGE BODY RDB$PROFILER
AS
^


CREATE PACKAGE BODY RDB$TIME_ZONE_UTIL
AS
^



SET TERM ; ^

