/******************************************************************************/
/****         Generated by IBExpert 2015.6.1.1 09.02.2026 23:46:11         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE '127.0.0.1/3052:c:\Programy12\MODYFIKACJE\INZYNIERKA\SOURCES\SERVER\bin\Win32\Debug_central\database\CENTRAL_WEIGHER.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN DATE_TIME AS
TIMESTAMP;

CREATE DOMAIN FLAG AS
SMALLINT;

CREATE DOMAIN NUMERIC_15_2 AS
NUMERIC(15,2);

CREATE DOMAIN TEXT_10 AS
VARCHAR(10);

CREATE DOMAIN TEXT_100 AS
VARCHAR(100);

CREATE DOMAIN TEXT_25 AS
VARCHAR(25);

CREATE DOMAIN TEXT_50 AS
VARCHAR(50);



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ADDRESSES_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_ADDRESSES_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_CUSTOMERS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_CUSTOMERS_LOCATIONS_ID TO 1;

CREATE GENERATOR GEN_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_PRODUCTS_LOCATIONS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUCTS_LOCATIONS_ID TO 0;

CREATE GENERATOR GEN_USERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_USERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ADDRESSESS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_CUSTOMERS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_ID TO 0;

CREATE GENERATOR GEN_WEIGHINGS_PRODUCTS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHINGS_PRODUCTS_ID TO 0;

CREATE GENERATOR GEN_WEIGHING_NUMBERS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_WEIGHING_NUMBERS_ID TO 0;



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE GET_ADDRESSES (
    ID_IN INTEGER)
RETURNS (
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_CUSTOMERS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    CUST_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_NEXT_WEIGHING_NO
RETURNS (
    WEIGHING_NO_OUT TEXT_25)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_PRODUCTS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    PROD_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE GET_WEIGHINGS (
    ID_IN INTEGER NOT NULL,
    ID_LOCATION_IN INTEGER)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    CAR_NO_OUT TEXT_25,
    TRAILER_NO_OUT TEXT_25,
    MASS_IN_OUT NUMERIC_15_2,
    DATE_IN_OUT DATE_TIME,
    MASS_OUT_OUT NUMERIC_15_2,
    DATE_OUT_OUT DATE_TIME,
    WEIGHING_TYPE_OUT SMALLINT,
    ID_USER_IN_OUT INTEGER,
    ID_USER_OUT_OUT INTEGER,
    ID_LOCATION_OUT INTEGER,
    ID_USER_INSERT_OUT INTEGER,
    ID_USER_MODIF_OUT INTEGER,
    MODIF_TIME_OUT DATE_TIME,
    IS_DELETED_OUT FLAG,
    PROD_ID_OUT INTEGER,
    PROD_WEIGHING_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG,
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG,
    CUST_ID_OUT INTEGER,
    CUST_WEIGHING_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_ADDRESS (
    ID_IN INTEGER NOT NULL,
    STREET_IN TEXT_50,
    HOUSE_NO_IN TEXT_10,
    LOCAL_NO_IN TEXT_10,
    POST_CODE_IN TEXT_10,
    CITY_IN TEXT_50,
    COUNTRY_IN TEXT_50,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_CUSTOMER (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    NIP_IN TEXT_25,
    PHONE_NO_IN TEXT_25,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_LOCATION (
    ID_IN INTEGER NOT NULL,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_PRODUCT (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    PRICE_IN NUMERIC_15_2,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_USER (
    ID_IN INTEGER NOT NULL,
    LOGIN_IN TEXT_50,
    USER_PASSWORD_IN TEXT_50,
    FIRST_NAME_IN TEXT_25,
    LAST_NAME_IN TEXT_25,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE PROCEDURE INSERT_UPDATE_WEIGHING (
    ID_IN INTEGER NOT NULL,
    CAR_NO_IN TEXT_25,
    TRAILER_NO_IN TEXT_25,
    MASS_IN_IN NUMERIC_15_2,
    DATE_IN_IN DATE_TIME,
    MASS_OUT_IN NUMERIC_15_2,
    DATE_OUT_IN DATE_TIME,
    WEIGHING_TYPE_IN SMALLINT,
    ID_CUSTOMER_IN INTEGER,
    ID_PRODUCT_IN INTEGER,
    ID_USER_IN_IN INTEGER,
    ID_USER_OUT_IN INTEGER,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    ERROR_CODE_OUT INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ADDRESSES (
    ID                 INTEGER NOT NULL,
    STREET             TEXT_50,
    HOUSE_NO           TEXT_10,
    LOCAL_NO           TEXT_10,
    POST_CODE          TEXT_10,
    CITY               TEXT_50,
    COUNTRY            TEXT_50,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE CUSTOMERS (
    ID                 INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    NIP                TEXT_25,
    PHONE_NO           TEXT_25,
    ID_ADDRESS         INTEGER,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE CUSTOMERS_LOCATIONS (
    ID           INTEGER NOT NULL,
    ID_CUSTOMER  INTEGER NOT NULL,
    ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE LOCATIONS (
    ID                 INTEGER NOT NULL,
    ID_ADDRESS         INTEGER,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE PRODUCTS (
    ID                 INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    PRICE              NUMERIC_15_2,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE PRODUCTS_LOCATIONS (
    ID           INTEGER NOT NULL,
    ID_PRODUCT   INTEGER NOT NULL,
    ID_LOCATION  INTEGER NOT NULL
);

CREATE TABLE USERS (
    ID                 INTEGER NOT NULL,
    LOGIN              TEXT_50,
    USER_PASSWORD      TEXT_100,
    FIRST_NAME         TEXT_25,
    LAST_NAME          TEXT_25,
    ID_LOCATION        INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE WEIGHING_NUMBERS (
    ID            INTEGER NOT NULL,
    WEIGHINGS_NO  INTEGER NOT NULL,
    MONTH_NO      INTEGER NOT NULL,
    YEAR_NO       INTEGER NOT NULL
);

CREATE TABLE WEIGHINGS (
    ID                    INTEGER NOT NULL,
    WEIGHING_NO           TEXT_25,
    CAR_NO                TEXT_25,
    TRAILER_NO            TEXT_25,
    MASS_IN               NUMERIC_15_2,
    DATE_IN               DATE_TIME,
    MASS_OUT              NUMERIC_15_2,
    DATE_OUT              DATE_TIME,
    WEIGHING_TYPE         SMALLINT,
    ID_CUSTOMER           INTEGER,
    ID_CUSTOMER_WEIGHING  INTEGER,
    ID_PRODUCT            INTEGER,
    ID_PRODUCT_WEIGHING   INTEGER,
    ID_USER_IN            INTEGER,
    ID_USER_OUT           INTEGER,
    ID_LOCATION           INTEGER,
    ID_USER_INSERT        INTEGER,
    ID_USER_MODIF         INTEGER,
    MODIFICATION_TIME     DATE_TIME,
    IS_DELETED            FLAG
);

CREATE TABLE WEIGHINGS_ADDRESSESS (
    ID                 INTEGER NOT NULL,
    ID_ADDRESS         INTEGER NOT NULL,
    STREET             TEXT_50,
    HOUSE_NO           TEXT_10,
    LOCAL_NO           TEXT_10,
    POST_CODE          TEXT_10,
    CITY               TEXT_50,
    COUNTRY            TEXT_50,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);

CREATE TABLE WEIGHINGS_CUSTOMERS (
    ID                   INTEGER NOT NULL,
    ID_CUSTOMER          INTEGER NOT NULL,
    CODE                 TEXT_10,
    NAME                 TEXT_50,
    NIP                  TEXT_25,
    PHONE_NO             TEXT_25,
    ID_ADDRESS_WEIGHING  INTEGER,
    ID_USER_INSERT       INTEGER,
    ID_USER_MODIF        INTEGER,
    MODIFICATION_TIME    DATE_TIME,
    IS_DELETED           FLAG
);

CREATE TABLE WEIGHINGS_PRODUCTS (
    ID                 INTEGER NOT NULL,
    ID_PRODUCT         INTEGER NOT NULL,
    CODE               TEXT_10,
    NAME               TEXT_50,
    PRICE              NUMERIC_15_2,
    ID_USER_INSERT     INTEGER,
    ID_USER_MODIF      INTEGER,
    MODIFICATION_TIME  DATE_TIME,
    IS_DELETED         FLAG
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ADDRESSES ADD CONSTRAINT PK_ADDRESSES PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS_LOCATIONS ADD CONSTRAINT PK_CUSTOMERS_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE PRODUCTS_LOCATIONS ADD CONSTRAINT PK_PRODUCTS_LOCATIONS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS ADD CONSTRAINT PK_WEIGHINGS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_ADDRESSESS ADD CONSTRAINT PK_WEIGHINGS_ADDRESSESS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_CUSTOMERS ADD CONSTRAINT PK_WEIGHINGS_CUSTOMERS PRIMARY KEY (ID);
ALTER TABLE WEIGHINGS_PRODUCTS ADD CONSTRAINT PK_WEIGHINGS_PRODUCTS PRIMARY KEY (ID);
ALTER TABLE WEIGHING_NUMBERS ADD CONSTRAINT PK_WEIGHING_NUMBERS PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ADDRESSES_BI */
CREATE TRIGGER ADDRESSES_BI FOR ADDRESSES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_addresses_id,1);
end
^

/* Trigger: CUSTOMERS_BI */
CREATE TRIGGER CUSTOMERS_BI FOR CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_id,1);
end
^

/* Trigger: CUSTOMERS_LOCATIONS_BI */
CREATE TRIGGER CUSTOMERS_LOCATIONS_BI FOR CUSTOMERS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_customers_locations_id,1);
end
^

/* Trigger: LOCATIONS_BI */
CREATE TRIGGER LOCATIONS_BI FOR LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_locations_id,1);
end
^

/* Trigger: PRODUCTS_BI */
CREATE TRIGGER PRODUCTS_BI FOR PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_id,1);
end
^

/* Trigger: PRODUCTS_LOCATIONS_BI */
CREATE TRIGGER PRODUCTS_LOCATIONS_BI FOR PRODUCTS_LOCATIONS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_products_locations_id,1);
end
^

/* Trigger: USERS_BI */
CREATE TRIGGER USERS_BI FOR USERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_users_id,1);
end
^

/* Trigger: WEIGHINGS_ADDRESSESS_BI */
CREATE TRIGGER WEIGHINGS_ADDRESSESS_BI FOR WEIGHINGS_ADDRESSESS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_addressess_id,1);
end
^

/* Trigger: WEIGHINGS_BI */
CREATE TRIGGER WEIGHINGS_BI FOR WEIGHINGS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_id,1);
end
^

/* Trigger: WEIGHINGS_CUSTOMERS_BI */
CREATE TRIGGER WEIGHINGS_CUSTOMERS_BI FOR WEIGHINGS_CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_customers_id,1);
end
^

/* Trigger: WEIGHINGS_PRODUCTS_BI */
CREATE TRIGGER WEIGHINGS_PRODUCTS_BI FOR WEIGHINGS_PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighings_products_id,1);
end
^

/* Trigger: WEIGHING_NUMBERS_BI */
CREATE TRIGGER WEIGHING_NUMBERS_BI FOR WEIGHING_NUMBERS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_weighing_numbers_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE GET_ADDRESSES (
    ID_IN INTEGER)
RETURNS (
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
      ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED
    FROM ADDRESSES
    WHERE
      (ID = :id_in) and (is_deleted = 0)
    INTO
      :address_id_out, :address_street_out, :address_house_no_out,
      :address_local_no_out, :address_post_code_out, :address_city_out,
      :address_country_out, :address_id_user_insert_out, :address_id_user_modif_out,
      :address_modif_time_out, :address_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
      ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED
    FROM ADDRESSES
    WHERE
      (is_deleted = 0)
    INTO
      :address_id_out, :address_street_out, :address_house_no_out,
      :address_local_no_out, :address_post_code_out, :address_city_out,
      :address_country_out, :address_id_user_insert_out, :address_id_user_modif_out,
      :address_modif_time_out, :address_is_deleted_out
    do begin
      suspend;
      address_id_out = null; address_street_out = null; address_house_no_out = null;
      address_local_no_out = null; address_post_code_out = null; address_city_out = null;
      address_country_out = null; address_id_user_insert_out = null; address_id_user_modif_out = null;
      address_modif_time_out = null; address_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_CUSTOMERS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    CUST_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      C.ID, C.CODE, C.NAME, C.NIP, C.PHONE_NO, C.ID_ADDRESS, C.ID_USER_INSERT,
      C.ID_USER_MODIF, C.MODIFICATION_TIME, C.IS_DELETED
    FROM customers C
    LEFT join customers_locations CL on CL.id_customer = C.ID
    WHERE
      (C.ID = :id_in) and (C.is_deleted = 0) and (coalesce(CL.id_location, 0) = :id_location_in)
    INTO
      :cust_id_out, :cust_code_out, :cust_name_out, :cust_nip_out, :cust_phone_no_out,
      :cust_id_address_out, :cust_id_user_insert_out, :cust_id_user_modif_out,
      :cust_modif_time_out, :cust_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      C.ID, C.CODE, C.NAME, C.NIP, C.PHONE_NO, C.ID_ADDRESS, C.ID_USER_INSERT,
      C.ID_USER_MODIF, C.MODIFICATION_TIME, C.IS_DELETED
    FROM customers C
    LEFT join customers_locations CL on CL.id_customer = C.ID
    WHERE
      (C.is_deleted = 0) and (coalesce(CL.id_location, 0) = :id_location_in)
    INTO
      :cust_id_out, :cust_code_out, :cust_name_out, :cust_nip_out, :cust_phone_no_out,
      :cust_id_address_out, :cust_id_user_insert_out, :cust_id_user_modif_out,
      :cust_modif_time_out, :cust_is_deleted_out
    do begin
      suspend;
      cust_id_out = null; cust_code_out = null; cust_name_out = null; cust_nip_out = null;
      cust_phone_no_out = null; cust_id_address_out = null; cust_id_user_insert_out = null;
      cust_id_user_modif_out = null; cust_modif_time_out = null; cust_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_NEXT_WEIGHING_NO
RETURNS (
    WEIGHING_NO_OUT TEXT_25)
AS
declare variable TMP_MONTH integer;
declare variable TMP_YEAR integer;
declare variable TMP_DT DATE_TIME;
declare variable TMP_WEIGHING_NO integer;
begin
  tmp_dt = 'now';
  tmp_year = extract(year from tmp_dt);
  tmp_month = extract(month from tmp_dt);

  select
    weighings_no
  from weighing_numbers
  where
    (month_no = :tmp_month) and (year_no = :tmp_year)
  into
    :tmp_weighing_no;

  if (coalesce(:tmp_weighing_no, 0) = 0) then
  begin
    tmp_weighing_no = 1;
    INSERT INTO WEIGHING_NUMBERS
      (WEIGHINGS_NO, MONTH_NO, YEAR_NO)
    VALUES
      (:tmp_weighing_no, :tmp_month, :tmp_year);
  end else
  begin
    tmp_weighing_no = :tmp_weighing_no + 1;
    UPDATE weighing_numbers
    SET weighings_no = :tmp_weighing_no
    where
      (month_no = :tmp_month) and (year_no = :tmp_year);
  end

  weighing_no_out = LEFT(CAST(tmp_weighing_no as text_10) || '/' || cast(tmp_month as varchar(5)) || '/' || CAST(tmp_year as varchar(5)), 25);
  suspend;
end^


ALTER PROCEDURE GET_PRODUCTS (
    ID_IN INTEGER,
    ID_LOCATION_IN INTEGER NOT NULL)
RETURNS (
    PROD_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG)
AS
begin
  if (:id_in != 0) then
  begin
    SELECT
      P.ID, P.CODE, P.NAME, P.PRICE, P.ID_USER_INSERT, P.ID_USER_MODIF,
      P.MODIFICATION_TIME, P.IS_DELETED
    FROM products P
    LEFT join products_locations PL on PL.id_product = P.ID
    WHERE
      (P.ID = :id_in) and (P.is_deleted = 0) and (coalesce(PL.id_location, 0) = :id_location_in)
    INTO
      :prod_id_out, :prod_code_out, :prod_name_out, :prod_price_out, :prod_id_user_insert_out,
      :prod_id_user_modif_out, :prod_modif_time_out, :prod_is_deleted_out;
    suspend;
    exit;
  end else
  begin
    FOR SELECT
      P.ID, P.CODE, P.NAME, P.PRICE, P.ID_USER_INSERT, P.ID_USER_MODIF,
      P.MODIFICATION_TIME, P.IS_DELETED
    FROM products P
    LEFT join products_locations PL on PL.id_product = P.ID
    WHERE
      (P.is_deleted = 0) and (coalesce(PL.id_location, 0) = :id_location_in)
    INTO
      :prod_id_out, :prod_code_out, :prod_name_out, :prod_price_out, :prod_id_user_insert_out,
      :prod_id_user_modif_out, :prod_modif_time_out, :prod_is_deleted_out
    do begin
      suspend;
      prod_id_out = null; prod_code_out = null; prod_name_out = null; prod_price_out = null;
      prod_id_user_insert_out = null; prod_id_user_modif_out = null; prod_modif_time_out = null;
      prod_is_deleted_out = null;
    end
  end
end^


ALTER PROCEDURE GET_WEIGHINGS (
    ID_IN integer not null,
    ID_LOCATION_IN integer)
returns (
    ID_OUT integer,
    WEIGHING_NO_OUT TEXT_25,
    CAR_NO_OUT TEXT_25,
    TRAILER_NO_OUT TEXT_25,
    MASS_IN_OUT NUMERIC_15_2,
    DATE_IN_OUT DATE_TIME,
    MASS_OUT_OUT NUMERIC_15_2,
    DATE_OUT_OUT DATE_TIME,
    WEIGHING_TYPE_OUT smallint,
    ID_USER_IN_OUT integer,
    ID_USER_OUT_OUT integer,
    ID_LOCATION_OUT integer,
    ID_USER_INSERT_OUT integer,
    ID_USER_MODIF_OUT integer,
    MODIF_TIME_OUT DATE_TIME,
    IS_DELETED_OUT FLAG,
    PROD_ID_OUT INTEGER,
    PROD_WEIGHING_ID_OUT INTEGER,
    PROD_CODE_OUT TEXT_10,
    PROD_NAME_OUT TEXT_50,
    PROD_PRICE_OUT NUMERIC_15_2,
    PROD_ID_USER_INSERT_OUT INTEGER,
    PROD_ID_USER_MODIF_OUT INTEGER,
    PROD_MODIF_TIME_OUT DATE_TIME,
    PROD_IS_DELETED_OUT FLAG,
    ADDRESS_ID_OUT INTEGER,
    ADDRESS_STREET_OUT TEXT_50,
    ADDRESS_HOUSE_NO_OUT TEXT_10,
    ADDRESS_LOCAL_NO_OUT TEXT_10,
    ADDRESS_POST_CODE_OUT TEXT_10,
    ADDRESS_CITY_OUT TEXT_50,
    ADDRESS_COUNTRY_OUT TEXT_50,
    ADDRESS_ID_USER_INSERT_OUT INTEGER,
    ADDRESS_ID_USER_MODIF_OUT INTEGER,
    ADDRESS_MODIF_TIME_OUT DATE_TIME,
    ADDRESS_IS_DELETED_OUT FLAG,
    CUST_ID_OUT INTEGER,
    CUST_WEIGHING_ID_OUT INTEGER,
    CUST_CODE_OUT TEXT_10,
    CUST_NAME_OUT TEXT_50,
    CUST_NIP_OUT TEXT_25,
    CUST_PHONE_NO_OUT TEXT_25,
    CUST_ID_ADDRESS_OUT INTEGER,
    CUST_ID_USER_INSERT_OUT INTEGER,
    CUST_ID_USER_MODIF_OUT INTEGER,
    CUST_MODIF_TIME_OUT DATE_TIME,
    CUST_IS_DELETED_OUT FLAG)
as
begin
  if (:id_in != 0) then
  begin
    SELECT
       W.ID, W.WEIGHING_NO, W.CAR_NO, W.TRAILER_NO, W.MASS_IN, W.DATE_IN,
       W.MASS_OUT, W.DATE_OUT, W.WEIGHING_TYPE, W.ID_USER_IN, W.ID_USER_OUT,
       W.ID_LOCATION, W.ID_USER_INSERT, W.ID_USER_MODIF, W.MODIFICATION_TIME,
       W.IS_DELETED,

       WP.ID, WP.ID_PRODUCT, WP.CODE, WP.NAME, WP.PRICE, WP.ID_USER_INSERT,
       WP.ID_USER_MODIF, WP.MODIFICATION_TIME, WP.IS_DELETED,

       WC.ID, WC.ID_CUSTOMER, WC.CODE, WC.NAME, WC.NIP, WC.PHONE_NO, WC.ID_ADDRESS_WEIGHING,
       WC.ID_USER_INSERT, WC.ID_USER_MODIF, WC.MODIFICATION_TIME, WC.IS_DELETED,

       ADDRSS.ID, ADDRSS.STREET, ADDRSS.HOUSE_NO, ADDRSS.LOCAL_NO, ADDRSS.POST_CODE,
       ADDRSS.CITY, ADDRSS.COUNTRY, ADDRSS.ID_USER_INSERT, ADDRSS.ID_USER_MODIF,
       ADDRSS.MODIFICATION_TIME, ADDRSS.IS_DELETED
    FROM
      WEIGHINGS W
    LEFT JOIN WEIGHINGS_PRODUCTS WP ON WP.ID = W.ID_PRODUCT_WEIGHING
    LEFT JOIN WEIGHINGS_CUSTOMERS WC ON WC.ID = W.ID_CUSTOMER_WEIGHING
    LEFT JOIN ADDRESSES ADDRSS ON ADDRSS.ID = WC.id_address_weighing
    WHERE
      (W.ID = :id_in) and (W.is_deleted = 0) and (coalesce(W.id_location, 0) = :id_location_in)
    INTO
      :ID_OUT, :WEIGHING_NO_OUT, :CAR_NO_OUT, :TRAILER_NO_OUT, :MASS_IN_OUT, :DATE_IN_OUT,
      :MASS_OUT_OUT, :DATE_OUT_OUT, :WEIGHING_TYPE_OUT, :ID_USER_IN_OUT, :ID_USER_OUT_OUT,
      :ID_LOCATION_OUT, :ID_USER_INSERT_OUT, :ID_USER_MODIF_OUT, :MODIF_TIME_OUT, :IS_DELETED_OUT,

      :PROD_WEIGHING_ID_OUT, :PROD_ID_OUT, :PROD_CODE_OUT, :PROD_NAME_OUT, :PROD_PRICE_OUT,
      :PROD_ID_USER_INSERT_OUT, :PROD_ID_USER_MODIF_OUT, :PROD_MODIF_TIME_OUT,
      :PROD_IS_DELETED_OUT,

      :CUST_WEIGHING_ID_OUT, :CUST_ID_OUT, :CUST_CODE_OUT, :CUST_NAME_OUT,
      :CUST_NIP_OUT, :CUST_PHONE_NO_OUT, :CUST_ID_ADDRESS_OUT, :CUST_ID_USER_INSERT_OUT,
      :CUST_ID_USER_MODIF_OUT, :CUST_MODIF_TIME_OUT, :CUST_IS_DELETED_OUT,

      :ADDRESS_ID_OUT, :ADDRESS_STREET_OUT, :ADDRESS_HOUSE_NO_OUT,
      :ADDRESS_LOCAL_NO_OUT, :ADDRESS_POST_CODE_OUT, :ADDRESS_CITY_OUT,
      :ADDRESS_COUNTRY_OUT, :ADDRESS_ID_USER_INSERT_OUT, :ADDRESS_ID_USER_MODIF_OUT,
      :ADDRESS_MODIF_TIME_OUT, :ADDRESS_IS_DELETED_OUT;

    suspend;
    exit;
  end else
  begin
    FOR SELECT
       W.ID, W.WEIGHING_NO, W.CAR_NO, W.TRAILER_NO, W.MASS_IN, W.DATE_IN,
       W.MASS_OUT, W.DATE_OUT, W.WEIGHING_TYPE, W.ID_USER_IN, W.ID_USER_OUT,
       W.ID_LOCATION, W.ID_USER_INSERT, W.ID_USER_MODIF, W.MODIFICATION_TIME,
       W.IS_DELETED,

       WP.ID, WP.ID_PRODUCT, WP.CODE, WP.NAME, WP.PRICE, WP.ID_USER_INSERT,
       WP.ID_USER_MODIF, WP.MODIFICATION_TIME, WP.IS_DELETED,

       WC.ID, WC.ID_CUSTOMER, WC.CODE, WC.NAME, WC.NIP, WC.PHONE_NO, WC.ID_ADDRESS_WEIGHING,
       WC.ID_USER_INSERT, WC.ID_USER_MODIF, WC.MODIFICATION_TIME, WC.IS_DELETED,

       ADDRSS.ID, ADDRSS.STREET, ADDRSS.HOUSE_NO, ADDRSS.LOCAL_NO, ADDRSS.POST_CODE,
       ADDRSS.CITY, ADDRSS.COUNTRY, ADDRSS.ID_USER_INSERT, ADDRSS.ID_USER_MODIF,
       ADDRSS.MODIFICATION_TIME, ADDRSS.IS_DELETED
    FROM
      WEIGHINGS W
    LEFT JOIN WEIGHINGS_PRODUCTS WP ON WP.ID = W.ID_PRODUCT_WEIGHING
    LEFT JOIN WEIGHINGS_CUSTOMERS WC ON WC.ID = W.ID_CUSTOMER_WEIGHING
    LEFT JOIN ADDRESSES ADDRSS ON ADDRSS.ID = WC.id_address_weighing
    WHERE
      (W.is_deleted = 0) and (coalesce(W.id_location, 0) = :id_location_in)
    INTO
      :ID_OUT, :WEIGHING_NO_OUT, :CAR_NO_OUT, :TRAILER_NO_OUT, :MASS_IN_OUT, :DATE_IN_OUT,
      :MASS_OUT_OUT, :DATE_OUT_OUT, :WEIGHING_TYPE_OUT, :ID_USER_IN_OUT, :ID_USER_OUT_OUT,
      :ID_LOCATION_OUT, :ID_USER_INSERT_OUT, :ID_USER_MODIF_OUT, :MODIF_TIME_OUT, :IS_DELETED_OUT,

      :PROD_WEIGHING_ID_OUT, :PROD_ID_OUT, :PROD_CODE_OUT, :PROD_NAME_OUT, :PROD_PRICE_OUT,
      :PROD_ID_USER_INSERT_OUT, :PROD_ID_USER_MODIF_OUT, :PROD_MODIF_TIME_OUT,
      :PROD_IS_DELETED_OUT,

      :CUST_WEIGHING_ID_OUT, :CUST_ID_OUT, :CUST_CODE_OUT, :CUST_NAME_OUT,
      :CUST_NIP_OUT, :CUST_PHONE_NO_OUT, :CUST_ID_ADDRESS_OUT, :CUST_ID_USER_INSERT_OUT,
      :CUST_ID_USER_MODIF_OUT, :CUST_MODIF_TIME_OUT, :CUST_IS_DELETED_OUT,

      :ADDRESS_ID_OUT, :ADDRESS_STREET_OUT, :ADDRESS_HOUSE_NO_OUT,
      :ADDRESS_LOCAL_NO_OUT, :ADDRESS_POST_CODE_OUT, :ADDRESS_CITY_OUT,
      :ADDRESS_COUNTRY_OUT, :ADDRESS_ID_USER_INSERT_OUT, :ADDRESS_ID_USER_MODIF_OUT,
      :ADDRESS_MODIF_TIME_OUT, :ADDRESS_IS_DELETED_OUT
    do begin
      suspend;
      ID_OUT = null; WEIGHING_NO_OUT = null; CAR_NO_OUT = null; TRAILER_NO_OUT = null; MASS_IN_OUT = null;
      DATE_IN_OUT = null; MASS_OUT_OUT = null; DATE_OUT_OUT = null; WEIGHING_TYPE_OUT = null;
      ID_USER_IN_OUT = null; ID_USER_OUT_OUT = null; ID_LOCATION_OUT = null; ID_USER_INSERT_OUT = null;
      ID_USER_MODIF_OUT = null; MODIF_TIME_OUT = null; IS_DELETED_OUT = null;
        
      PROD_WEIGHING_ID_OUT = null; PROD_ID_OUT = null; PROD_CODE_OUT = null; PROD_NAME_OUT = null;
      PROD_PRICE_OUT = null; PROD_ID_USER_INSERT_OUT = null; PROD_ID_USER_MODIF_OUT = null;
      PROD_MODIF_TIME_OUT = null; PROD_IS_DELETED_OUT = null;
        
      CUST_WEIGHING_ID_OUT = null; CUST_ID_OUT = null; CUST_CODE_OUT = null;
      CUST_NAME_OUT = null; CUST_NIP_OUT = null; CUST_PHONE_NO_OUT = null;
      CUST_ID_ADDRESS_OUT = null; CUST_ID_USER_INSERT_OUT = null; CUST_ID_USER_MODIF_OUT = null;
      CUST_MODIF_TIME_OUT = null; CUST_IS_DELETED_OUT = null;
        
      ADDRESS_ID_OUT = null; ADDRESS_STREET_OUT = null;
      ADDRESS_HOUSE_NO_OUT = null; ADDRESS_LOCAL_NO_OUT = null;
      ADDRESS_POST_CODE_OUT = null; ADDRESS_CITY_OUT = null;
      ADDRESS_COUNTRY_OUT = null; ADDRESS_ID_USER_INSERT_OUT = null;
      ADDRESS_ID_USER_MODIF_OUT = null; ADDRESS_MODIF_TIME_OUT = null;
      ADDRESS_IS_DELETED_OUT = null;
    end
  end
end^


ALTER PROCEDURE INSERT_UPDATE_ADDRESS (
    ID_IN INTEGER NOT NULL,
    STREET_IN TEXT_50,
    HOUSE_NO_IN TEXT_10,
    LOCAL_NO_IN TEXT_10,
    POST_CODE_IN TEXT_10,
    CITY_IN TEXT_50,
    COUNTRY_IN TEXT_50,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_addresses_id, 1);
    INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES (:id_out, :street_in, :house_no_in, :local_no_in, :post_code_in, :city_in, :country_in, :id_user_in, :id_user_in, 'NOW', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE ADDRESSES
      SET STREET = :street_in,
          HOUSE_NO = :house_no_in,
          LOCAL_NO = :local_no_in,
          POST_CODE = :post_code_in,
          CITY = :city_in,
          COUNTRY = :country_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE addresses
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_CUSTOMER (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    NIP_IN TEXT_25,
    PHONE_NO_IN TEXT_25,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_customers_id, 1);
    INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES(:id_out, :code_in, :name_in, :nip_in, :phone_no_in, :id_address_in, :id_user_in, :id_user_in, 'now', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE customers
      SET CODE = :CODE_IN,
          NAME = :NAME_IN,
          NIP = :NIP_IN,
          PHONE_NO = :PHONE_NO_IN,
          ID_ADDRESS = :ID_ADDRESS_IN,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE customers
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_LOCATION (
    ID_IN INTEGER NOT NULL,
    ID_ADDRESS_IN INTEGER,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_locations_id, 1);
    INSERT INTO LOCATIONS (ID, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES (:id_out, :id_address_in, :id_user_in, :id_user_in, 'now', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE LOCATIONS
      SET ID_ADDRESS = :id_address_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE locations
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_PRODUCT (
    ID_IN INTEGER NOT NULL,
    CODE_IN TEXT_10,
    NAME_IN TEXT_50,
    PRICE_IN NUMERIC_15_2,
    IS_DELETED_IN FLAG,
    ID_USER_IN INTEGER NOT NULL)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_products_id, 1);
    INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES(:id_out, :code_in, :name_in, :price_in, :id_user_in, :id_user_in, 'NOW', 0);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE PRODUCTS
      SET CODE = :code_in,
          NAME = :name_in,
          PRICE = :price_in,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE PRODUCTS
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_USER (
    ID_IN INTEGER NOT NULL,
    LOGIN_IN TEXT_50,
    USER_PASSWORD_IN TEXT_100,
    FIRST_NAME_IN TEXT_25,
    LAST_NAME_IN TEXT_25,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER)
AS
begin
  if (:id_in = 0) then
  begin
    id_out = gen_id(gen_users_id, 1);
    INSERT INTO USERS (ID, LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME, ID_LOCATION, MODIFICATION_TIME, IS_DELETED)
      VALUES (:ID_OUT, :LOGIN_IN, :USER_PASSWORD_IN, :FIRST_NAME_IN, :LAST_NAME_IN, :ID_LOCATION_IN, 'now', :IS_DELETED_IN);
  end else
  begin
    id_out = :id_in;
    if (:is_deleted_in = 0) then
    begin
      UPDATE users
      SET LOGIN = :login_in,
          USER_PASSWORD = :user_password_in,
          FIRST_NAME = :first_name_in,
          LAST_NAME = :last_name_in,
          ID_LOCATION = :id_location_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (is_deleted = 0);
    end else
    begin
      UPDATE users
      SET is_deleted = 1,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);
    end
  end
  suspend;
end^


ALTER PROCEDURE INSERT_UPDATE_WEIGHING (
    ID_IN INTEGER NOT NULL,
    CAR_NO_IN TEXT_25,
    TRAILER_NO_IN TEXT_25,
    MASS_IN_IN NUMERIC_15_2,
    DATE_IN_IN DATE_TIME,
    MASS_OUT_IN NUMERIC_15_2,
    DATE_OUT_IN DATE_TIME,
    WEIGHING_TYPE_IN SMALLINT,
    ID_CUSTOMER_IN INTEGER,
    ID_PRODUCT_IN INTEGER,
    ID_USER_IN_IN INTEGER,
    ID_USER_OUT_IN INTEGER,
    ID_LOCATION_IN INTEGER,
    IS_DELETED_IN FLAG)
RETURNS (
    ID_OUT INTEGER,
    WEIGHING_NO_OUT TEXT_25,
    ERROR_CODE_OUT INTEGER)
AS
declare variable TMP_WEIGHING_NO TEXT_25;
declare variable TMP_CUSTOMER_CODE TEXT_10;
declare variable TMP_CUSTOMER_NAME TEXT_50;
declare variable TMP_CUSTOMER_NIP TEXT_25;
declare variable TMP_CUSTOMER_PHONE_NO TEXT_25;
declare variable TMP_ID_ADDRESS integer;
declare variable TMP_ADDRESS_STREET TEXT_50;
declare variable TMP_ADDRESS_HOUSE_NO TEXT_10;
declare variable TMP_ADDRESS_LOCAL_NO TEXT_10;
declare variable TMP_ADDRESS_POST_CODE TEXT_10;
declare variable TMP_ADDRESS_CITY TEXT_50;
declare variable TMP_ADDRESS_COUNTRY TEXT_50;
declare variable TMP_PRODUCT_CODE TEXT_10;
declare variable TMP_PRODUCT_NAME TEXT_50;
declare variable TMP_PRODUCT_PRICE NUMERIC_15_2;
declare variable TMP_ID1 integer;
declare variable TMP_ID2 integer;
begin
  id_out = 0;
  error_code_out = 1;
  weighing_no_out = '';
  if (:id_in = 0) then
  begin
    if (:weighing_type_in = 1) then
    begin
      error_code_out = -1; -- drugie wazenie przy braku pierwszego wazenia
      suspend;
      exit;
    end else if (:weighing_type_in in (0, 2)) then
    begin
      -- if (coalesce(:id_location_in, 0) = 0)  then
      -- begin
      --   error_code_out = -2;
      --   suspend;
      --   exit;
      -- end

      -- POBRANIE DANYCH KARTOTEK
      -- KONTRAHENT
      if (coalesce(:id_customer_in, 0) = 0)  then
      begin
        error_code_out = -3;
        suspend;
        exit;
      end

      SELECT
        CUST_CODE_OUT, CUST_NAME_OUT, CUST_NIP_OUT, CUST_PHONE_NO_OUT, CUST_ID_ADDRESS_OUT
      FROM get_customers(:id_customer_in, :id_location_in)
      INTO
        :tmp_customer_code, :tmp_customer_name, :tmp_customer_nip, :tmp_customer_phone_no,
        :tmp_id_address;

      SELECT
        ADDRESS_STREET_OUT, ADDRESS_HOUSE_NO_OUT, ADDRESS_LOCAL_NO_OUT, ADDRESS_POST_CODE_OUT,
        ADDRESS_CITY_OUT, ADDRESS_COUNTRY_OUT
      FROM get_addresses(:tmp_id_address)
      INTO
        :tmp_address_street, :tmp_address_house_no, :tmp_address_local_no, :tmp_address_post_code,
        :tmp_address_city, :tmp_address_country;

      -- PRODUKT
      if (coalesce(:id_product_in, 0) = 0)  then
      begin
        error_code_out = -4;
        suspend;
        exit;
      end

      SELECT
        PROD_CODE_OUT, PROD_NAME_OUT, PROD_PRICE_OUT
      FROM get_products(:id_product_in, :id_location_in)
      INTO
        :tmp_product_code, :tmp_product_name, :tmp_product_price;

      -- insert adres
      tmp_id1 = gen_id(gen_weighings_addressess_id, 1);
      INSERT INTO WEIGHINGS_ADDRESSESS
        (ID, ID_ADDRESS, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT,
         ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES
        (:tmp_id1, :tmp_id_address, :tmp_address_street, :tmp_address_house_no, :tmp_address_local_no,
         :tmp_address_post_code, :tmp_address_city, :tmp_address_country, :id_user_in_in,
         :id_user_in_in, 'now', 0);

      -- insert customer
      tmp_id2 = gen_id(gen_weighings_customers_id, 1);
      INSERT INTO WEIGHINGS_CUSTOMERS
        (ID, ID_CUSTOMER, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS_WEIGHING, ID_USER_INSERT,
         ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
      VALUES
        (:tmp_id2, :id_customer_in, :tmp_customer_code, :tmp_customer_name, :tmp_customer_nip,
         :tmp_customer_phone_no, :tmp_id1, :id_user_in_in, :id_user_in_in, 'now', 0);

      -- insert product
      tmp_id1 = gen_id(gen_weighings_products_id, 1);
      INSERT INTO WEIGHINGS_PRODUCTS
        (ID, ID_PRODUCT, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME,
         IS_DELETED)
      VALUES
        (:tmp_id1, :id_product_in, :tmp_product_code, :tmp_product_name, :tmp_product_price,
         :id_user_in_in, :id_user_in_in, 'now', 0);

      -- numer wazenia
      SELECT weighing_no_out FROM get_next_weighing_no into :tmp_weighing_no;

      -- wazenie
      id_out = gen_id(gen_weighings_id, 1);
      if (:weighing_type_in = 0) then
      begin
        -- PIERWSZE WAZENIE
        INSERT INTO WEIGHINGS
          (ID, WEIGHING_NO, CAR_NO, TRAILER_NO, MASS_IN, DATE_IN, MASS_OUT, DATE_OUT, WEIGHING_TYPE,
           ID_CUSTOMER, ID_CUSTOMER_WEIGHING, ID_PRODUCT, ID_PRODUCT_WEIGHING, ID_USER_IN, ID_USER_OUT,
           ID_LOCATION, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
        VALUES
          (:id_out, :tmp_weighing_no, :car_no_in, :trailer_no_in, :mass_in_in, :date_in_in, NULL, NULL,
           :weighing_type_in, :id_customer_in, :tmp_id2, :id_product_in, :tmp_id1, :id_user_in_in, NULL,
           :id_location_in, :id_user_in_in, :id_user_in_in, 'now', 0);

        weighing_no_out = :tmp_weighing_no;
      end else if (:weighing_type_in = 2) then
      begin
        -- WAZENIE POJEDYNCZE
        INSERT INTO WEIGHINGS
          (ID, WEIGHING_NO, CAR_NO, TRAILER_NO, MASS_IN, DATE_IN, MASS_OUT, DATE_OUT, WEIGHING_TYPE,
           ID_CUSTOMER, ID_CUSTOMER_WEIGHING, ID_PRODUCT, ID_PRODUCT_WEIGHING, ID_USER_IN, ID_USER_OUT,
           ID_LOCATION, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED)
        VALUES
          (:id_out, :tmp_weighing_no, :car_no_in, :trailer_no_in, :mass_in_in, :date_in_in, :mass_out_in,
           NULL, :weighing_type_in, :id_customer_in, :tmp_id2, :id_product_in, :tmp_id1, :id_user_in_in,
           NULL, :id_location_in, :id_user_in_in, :id_user_in_in, 'now', 0);

        weighing_no_out = :tmp_weighing_no;
      end
    end
  end else
  begin
    if ((:is_deleted_in = 0) and (:weighing_type_in = 1)) then
    begin
      -- DRUGIE WAZENIE
      UPDATE weighings
      SET MASS_OUT = :mass_out_in,
          DATE_OUT = :date_out_in,
          ID_USER_OUT = :id_user_out_in,
          WEIGHING_TYPE = :weighing_type_in,
          ID_USER_MODIF = :id_user_out_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in) and (WEIGHING_TYPE = 0) and (is_deleted = 0);
      id_out = :id_in;
      select weighing_no from weighings where (ID = :id_in) into weighing_no_out;
    end else if (:is_deleted_in = 1) then
    begin
      UPDATE weighings
      SET is_deleted = 1,
          ID_USER_MODIF = :id_user_in_in,
          MODIFICATION_TIME = 'now'
      WHERE (ID = :id_in);

      id_out = :id_in;
      select weighing_no from weighings where (ID = :id_in) into weighing_no_out;
    end else
    begin
      error_code_out = -5;
    end
  end
  suspend;
end^



SET TERM ; ^

COMMIT WORK;

execute procedure INSERT_UPDATE_USER(0, 'Admin', 'ba0020fb1e1371474d5b328a53b87d2a05db7b8320f546baaf5dcbb248ef0c60', '', '', 0, 0);
execute procedure INSERT_UPDATE_USER(0, 'jan_kowalski', 'd9aea859a9b1432e4d8c4e90d6b4682e0acbd8b8950b6e0fa2af0c5aca01c528', 'Jan', 'Kowalski', 0, 0);

COMMIT WORK;

INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (1, '---', '---', '---', '---', '---', '---', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (2, 'ul. Przemyslowa', '12', '3', '00-101', 'Warszawa', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (3, 'ul. Hutnicza', '8', '1', '30-102', 'Krakow', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (4, 'ul. Towarowa', '15', '2', '50-103', 'Wroclaw', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (5, 'ul. Kolejowa', '21', '4', '90-104', 'Lodz', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (6, 'ul. Portowa', '7', '5', '80-105', 'Gdansk', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (7, 'ul. Morska', '44', '2', '81-106', 'Gdynia', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (8, 'ul. Baltycka', '9', '1', '81-107', 'Sopot', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (9, 'ul. Magazynowa', '18', '6', '60-108', 'Poznan', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (10, 'ul. Stoczniowa', '6', '2', '70-109', 'Szczecin', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (11, 'ul. Bema', '31', '7', '15-110', 'Bialystok', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (12, 'ul. Zbozowa', '14', '2', '20-111', 'Lublin', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (13, 'ul. Szybowa', '5', '3', '40-112', 'Katowice', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (14, 'ul. Spedycyjna', '16', '8', '35-113', 'Rzeszow', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (15, 'ul. Mostowa', '27', '4', '87-114', 'Torun', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (16, 'ul. Warmienska', '11', '2', '10-115', 'Olsztyn', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (17, 'ul. Odrzanska', '19', '5', '45-116', 'Opole', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (18, 'ul. Sandomierska', '23', '1', '25-117', 'Kielce', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (19, 'ul. Zachodnia', '10', '2', '65-118', 'Zielona Gora', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (20, 'ul. Fabryczna', '28', '6', '85-119', 'Bydgoszcz', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (21, 'ul. Warszawska', '33', '2', '26-120', 'Radom', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (22, 'ul. Koksowa', '13', '3', '42-121', 'Czestochowa', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (23, 'ul. Metalowa', '17', '5', '44-122', 'Gliwice', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (24, 'ul. Weglowa', '24', '1', '41-123', 'Zabrze', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (25, 'ul. Logistyczna', '20', '4', '41-124', 'Sosnowiec', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (26, 'ul. Mazowiecka', '29', '2', '09-125', 'Plock', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (27, 'ul. Nadbrzezna', '8', '3', '82-126', 'Elblag', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (28, 'ul. Transportowa', '22', '7', '66-127', 'Gorzow Wielkopolski', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (29, 'ul. Krakowska', '34', '1', '33-128', 'Tarnow', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (30, 'ul. Ciasna', '4', '2', '62-129', 'Kalisz', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (31, 'ul. Polnocna', '26', '5', '75-130', 'Koszalin', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (32, 'ul. Legnicka', '30', '6', '59-131', 'Legnica', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (33, 'ul. Mlynska', '12', '2', '76-132', 'Slupsk', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (34, 'ul. Augustowska', '18', '1', '16-133', 'Suwalki', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (35, 'ul. Rzeczna', '9', '3', '97-134', 'Piotrkow Trybunalski', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (36, 'ul. Gornicza', '14', '4', '62-135', 'Konin', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (37, 'ul. Chelminska', '25', '2', '86-136', 'Grudziadz', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (38, 'ul. Solankowa', '7', '1', '88-137', 'Inowroclaw', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (39, 'ul. Krotoszynska', '21', '2', '63-138', 'Ostrow Wielkopolski', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (40, 'ul. Bydgoska', '16', '5', '64-139', 'Pila', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (41, 'ul. Brzeska', '11', '3', '08-140', 'Siedlce', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (42, 'ul. Lwowska', '19', '2', '33-141', 'Nowy Sacz', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (43, 'ul. Hrubieszowska', '24', '4', '22-142', 'Zamosc', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (44, 'ul. Lubelska', '13', '6', '22-143', 'Chelm', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (45, 'ul. Karkonoska', '32', '1', '58-144', 'Jelenia Gora', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (46, 'ul. Skladowa', '6', '2', '64-145', 'Leszno', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (47, 'ul. Beskidzka', '27', '3', '43-146', 'Tychy', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (48, 'ul. 1 Maja', '15', '2', '41-147', 'Ruda Slaska', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (49, 'ul. Graniczna', '20', '8', '41-148', 'Dabrowa Gornicza', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (50, 'ul. Wysockiego', '18', '4', '58-149', 'Walbrzych', 'Polska', 1, 1, 'Now', 0);
INSERT INTO ADDRESSES (ID, STREET, HOUSE_NO, LOCAL_NO, POST_CODE, CITY, COUNTRY, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (51, 'ul. Sanocka', '10', '2', '37-150', 'Przemysl', 'Polska', 1, 1, 'Now', 0);


INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (1, '---', '---', '---', '---', 2, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (2, 'K1', 'Baltic Cargo Polska Sp. z o.o.', '501600102', '501600102', 2, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (3, 'K2', 'Centrum Kruszyw Polnoc Sp. z o.o.', '501600103', '501600103', 3, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (4, 'K3', 'Delta Recykling Sp. z o.o.', '501600104', '501600104', 4, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (5, 'K4', 'Eco Logis Sp. z o.o.', '501600105', '501600105', 5, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (6, 'K5', 'Ferro Mix Polska Sp. z o.o.', '501600106', '501600106', 6, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (7, 'K6', 'Grupa Transportowa Atlas Sp. z o.o.', '501600107', '501600107', 7, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (8, 'K7', 'Hutpol Serwis Sp. z o.o.', '501600108', '501600108', 8, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (9, 'K8', 'Inter Port Logistic Sp. z o.o.', '501600109', '501600109', 9, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (10, 'K9', 'Jantar Surowce Sp. z o.o.', '501600110', '501600110', 10, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (11, 'K10', 'Kopalnie Piasku Poludnie Sp. z o.o.', '501600111', '501600111', 11, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (12, 'K11', 'Lador Magazyny Sp. z o.o.', '501600112', '501600112', 12, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (13, 'K12', 'Metal Trade Polska Sp. z o.o.', '501600113', '501600113', 13, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (14, 'K13', 'Nord Cargo Service Sp. z o.o.', '501600114', '501600114', 14, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (15, 'K14', 'Omega Weighing Solutions Sp. z o.o.', '501600115', '501600115', 15, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (16, 'K15', 'Petro Mix Sp. z o.o.', '501600116', '501600116', 16, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (17, 'K16', 'Quick Transport Group Sp. z o.o.', '501600117', '501600117', 17, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (18, 'K17', 'Rol Market Polska Sp. z o.o.', '501600118', '501600118', 18, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (19, 'K18', 'Stal Bud Logistic Sp. z o.o.', '501600119', '501600119', 19, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (20, 'K19', 'Trans Kop Sp. z o.o.', '501600120', '501600120', 20, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (21, 'K20', 'Uni Recykling Sp. z o.o.', '501600121', '501600121', 21, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (22, 'K21', 'Vektor Cargo Sp. z o.o.', '501600122', '501600122', 22, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (23, 'K22', 'Weglo Hurt Sp. z o.o.', '501600123', '501600123', 23, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (24, 'K23', 'X Log Transport Sp. z o.o.', '501600124', '501600124', 24, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (25, 'K24', 'Yotta Surowce Sp. z o.o.', '501600125', '501600125', 25, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (26, 'K25', 'Zeton Polska Sp. z o.o.', '501600126', '501600126', 26, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (27, 'K26', 'Alfa Kopalnie Sp. z o.o.', '501600127', '501600127', 27, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (28, 'K27', 'Beton Mix Piatkowski Sp. z o.o.', '501600128', '501600128', 28, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (29, 'K28', 'Cargo East Sp. z o.o.', '501600129', '501600129', 29, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (30, 'K29', 'Drogbud Materialy Sp. z o.o.', '501600130', '501600130', 30, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (31, 'K30', 'Elpol Recykling Sp. z o.o.', '501600131', '501600131', 31, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (32, 'K31', 'Farm Agro Logistic Sp. z o.o.', '501600132', '501600132', 32, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (33, 'K32', 'Geo Kruszywa Sp. z o.o.', '501600133', '501600133', 33, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (34, 'K33', 'Hydro Trade Sp. z o.o.', '501600134', '501600134', 34, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (35, 'K34', 'Intra Steel Sp. z o.o.', '501600135', '501600135', 35, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (36, 'K35', 'Jura Transport Sp. z o.o.', '501600136', '501600136', 36, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (37, 'K36', 'Karo Magazyny Sp. z o.o.', '501600137', '501600137', 37, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (38, 'K37', 'Log Bud Partner Sp. z o.o.', '501600138', '501600138', 38, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (39, 'K38', 'Multi Cargo Polska Sp. z o.o.', '501600139', '501600139', 39, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (40, 'K39', 'Novum Port Sp. z o.o.', '501600140', '501600140', 40, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (41, 'K40', 'Orion Surowce Wtorne Sp. z o.o.', '501600141', '501600141', 41, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (42, 'K41', 'Prima Zboza Sp. z o.o.', '501600142', '501600142', 42, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (43, 'K42', 'Quartz Mineral Sp. z o.o.', '501600143', '501600143', 43, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (44, 'K43', 'Road Tank Service Sp. z o.o.', '501600144', '501600144', 44, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (45, 'K44', 'Sigma Metal Group Sp. z o.o.', '501600145', '501600145', 45, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (46, 'K45', 'Terra Logistic Sp. z o.o.', '501600146', '501600146', 46, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (47, 'K46', 'Urban Recykling Sp. z o.o.', '501600147', '501600147', 47, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (48, 'K47', 'Vistal Agro Sp. z o.o.', '501600148', '501600148', 48, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (49, 'K48', 'West Cargo Hub Sp. z o.o.', '501600149', '501600149', 49, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (50, 'K49', 'Zenit Transport i Surowce Sp. z o.o.', '501600150', '501600150', 50, 1, 1, 'NOW', 0);
INSERT INTO CUSTOMERS (ID, CODE, NAME, NIP, PHONE_NO, ID_ADDRESS, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (51, 'K50', 'Agro Trans Bis Sp. z o.o.', '501600101', '501600101', 51, 1, 1, 'NOW', 0);


INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (1, '---', '---', 0.00, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (2, 'P1', 'kruszywo bazaltowe 8-16 mm', 0.62, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (3, 'P2', 'kruszywo granitowe 16-32 mm', 0.68, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (4, 'P3', 'piasek plukany 0-2 mm', 0.29, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (5, 'P4', 'zwir rzeczny 2-8 mm', 0.41, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (6, 'P5', 'tluczen drogowy 31.5-63 mm', 0.57, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (7, 'P6', 'kliniec 4-31.5 mm', 0.49, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (8, 'P7', 'mial kamienny', 0.21, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (9, 'P8', 'wegiel orzech', 1.18, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (10, 'P9', 'wegiel groszek', 1.26, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (11, 'P10', 'koks przemyslowy', 1.74, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (12, 'P11', 'zlom stalowy wsadowy', 1.35, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (13, 'P12', 'zlom zeliwny', 1.12, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (14, 'P13', 'zlom aluminiowy', 4.90, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (15, 'P14', 'zlom miedziany', 24.50, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (16, 'P15', 'makulatura mieszana', 0.38, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (17, 'P16', 'tworzywa sztuczne przemial', 1.05, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (18, 'P17', 'szklo bezbarwne stluczka', 0.27, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (19, 'P18', 'szklo kolorowe stluczka', 0.24, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (20, 'P19', 'odpady budowlane mieszane', 0.19, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (21, 'P20', 'gruz ceglany', 0.17, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (22, 'P21', 'gruz betonowy', 0.18, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (23, 'P22', 'ziemia przesiana', 0.11, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (24, 'P23', 'humus', 0.14, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (25, 'P24', 'sol drogowa', 0.73, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (26, 'P25', 'wapno nawozowe', 0.46, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (27, 'P26', 'nawoz NPK 8-20-30', 2.35, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (28, 'P27', 'nawoz azotowy saletra', 2.12, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (29, 'P28', 'zboze pszenica', 0.98, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (30, 'P29', 'zboze kukurydza', 0.91, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (31, 'P30', 'zboze jeczmien', 0.86, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (32, 'P31', 'rzepak techniczny', 1.74, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (33, 'P32', 'biomasa drzewna zrabka', 0.44, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (34, 'P33', 'pellet przemyslowy', 1.32, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (35, 'P34', 'drewno odpadowe', 0.26, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (36, 'P35', 'asfalt frezowany', 0.31, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (37, 'P36', 'cement luzem', 0.89, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (38, 'P37', 'popiol lotny', 0.16, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (39, 'P38', 'gips syntetyczny', 0.22, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (40, 'P39', 'kamien wapienny 0-63 mm', 0.37, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (41, 'P40', 'dolomit kruszony', 0.43, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (42, 'P41', 'gabro 16-22 mm', 0.71, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (43, 'P42', 'granulat gumowy', 1.58, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (44, 'P43', 'koncentrat metali kolorowych', 6.80, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (45, 'P44', 'zluz ka wielkopiecowa', 0.13, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (46, 'P45', 'piasek suszony', 0.52, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (47, 'P46', 'mieszanka mineralno-asfaltowa', 0.94, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (48, 'P47', 'kruszywo recyklingowe 0-31.5 mm', 0.28, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (49, 'P48', 'kamien polny sortowany', 0.33, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (50, 'P49', 'nawoz wapniowo-magnezowy', 0.58, 1, 1, 'NOW', 0);
INSERT INTO PRODUCTS (ID, CODE, NAME, PRICE, ID_USER_INSERT, ID_USER_MODIF, MODIFICATION_TIME, IS_DELETED) VALUES (51, 'P50', 'pasza sypka przemyslowa', 1.09, 1, 1, 'NOW', 0);

COMMIT WORK;

SET GENERATOR GEN_ADDRESSES_ID TO 51;
SET GENERATOR GEN_CUSTOMERS_ID TO 51;
SET GENERATOR GEN_PRODUCTS_ID TO 51;
SET GENERATOR GEN_USERS_ID TO 2;

COMMIT WORK;